name: Python Script Runner with CSV Report
description: Runs a Python script, generates a CSV report and sends the report via email using Docker.

inputs:
  github-access-token:
    description: 'GitHub Access Token'
    required: true
  email-recipient:
    description: 'Email Recipient'
    required: true
  smtp-username:
    description: 'SMTP Username'
    required: true
  smtp-password:
    description: 'SMTP Password'
    required: true

runs:
  using: 'docker'
  image: 'Dockerfile'