on:
  push:
    branches:
    - main
    paths: 
    - 'app/**'
jobs:
  run_script:
    runs-on: ubuntu-latest
    name: Run Python script
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - name: Upgrade pip
        run: python -m pip install --upgrade pip
        
      - name: Upgrade setuptools and wheel
        run: pip install --upgrade setuptools wheel
        
      - name: Clear pip cache
        run: python -m pip cache purge
        
      - name: Install dependencies
        run: pip install -r requirements.txt 

      - name: Run script
        run: |
          python main.py
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.MY_TOKEN }} 

